name: Update Data Feed
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
    - name: Run conversion script
      run: python convert_to_json_xml.py
    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data-feed.json data-feed.xml
        git commit -m "Update data feed files" || echo "No changes to commit"
        git push
